apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bindu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: bindu-pv